### ISSUE TITLE
More things 

### ISSUE THREAD

**Issue by marineb** [EnMarche/transformer.en-marche.fr#4]
**TODO**
- [x] There should be promoted themes in the sidebar, with the gray "Voir plus" button like in the comps. Only this button should use the gray color combination [I just asked Remi if the feature was available]
- [x] All the mesures go to wnyc.org 🚫 :D they should only be a link if there's a URL in the field pulling from the URL field, show the arrow, and make it a link. Otherwise, no link. Most mesures won't have links for now
- [x] The last updated should be in Roboto, and if < 1 days, could we shows hours ?
- [x]  Links to cookies and terms : https://en-marche.fr/politique-cookies and https://en-marche.fr/mentions-legales

**BUGS**
- [x] When I search for publicité, it shows me the right mesures but also shows me the other themes empty. Ideally it wouldn't show me those themes if they don't have any matching mesures 

**Needs more specs**
- [ ] Intro text lost its roboto formatting. But wait till we have the final text  to fix it
- [ ] Add visualization of the progress on the presidency and the mesures
